[project]
name = "km003c-protocol-research"
version = "0.1.0"
description = "KM003C protocol reverse engineering and analysis tools"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jupyter>=1.0.0",
    "matplotlib>=3.5.0",
    "seaborn>=0.11.0",
    "numpy>=1.20.0",
    "usbpdpy>=0.1.0",
    "pyshark",
    "polars",
    "appdirs",
    "nest-asyncio",
]
